// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xdpfzuehmhrwmecufvwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcGZ6dWVobWhyd21lY3VmdndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTE5MjUsImV4cCI6MjA2OTAyNzkyNX0.qD_DMdKx6ySPoD0ihJ3QD-7waf1TCTYmmtspa2jTugE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});